Exception: STATUS_ACCESS_VIOLATION at rip=0018018D7AD
rax=000006FF00000000 rbx=000000000022B760 rcx=000006FF00000000
rdx=000000000022B808 rsi=000000000022B768 rdi=000006FF00000000
r8 =000000056B8ED864 r9 =0000000000000000 r10=000000054AA884A0
r11=000000000022B6A8 r12=000006FFFFAD4578 r13=000000054AA3B4D0
r14=000006FFFFAD45A0 r15=0000000000000000
rbp=0000000000000000 rsp=000000000022B5E8
program=C:\cygwin64\bin\python2.7.exe, pid 4896, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  0018018D7AD (00000000001, 6FFFFFC13F0, 000772CBAA6, 006003624D8)
00000000000  0054A9EAF2A (000772CBAA6, 6FFFF9A8908, 0000022B940, 0000022B970)
6FFFFAD45B0  0054A9EB33A (00000000000, 00482CC15C0, 6FFFFFC13F0, 00000000000)
0000022B940  0054A9EB8D8 (001800C7FF2, 00600206E10, 0000022BA60, 00000000001)
0000022B940  0054A9030AF (0056B8D384B, 00600362800, 00000000000, 6FF00000000)
0000022B940  0056B8D00D3 (00482CBF636, 6FFFF93CA50, 6FFFFA74328, 00000000000)
0000022B940  00482C73011 (006000EE960, 0060034D2C0, 0054AA3B4D0, 0054AAAFDA0)
00000000000  0056B8DB5E5 (006000EE960, 0054AA3B4D0, 006000EE960, 006000003F5)
00000000000  0056B8DB988 (006000EE960, 0054A9DB2E6, 00600028580, 6FFFFFEFB40)
00000000000  0054A9E0A37 (222928973FEEB611, 6FFFFFD28C0, 0060034D2C0, 00000000000)
0054AA3B4D0  0054A9DE11A (0054AAAFDB8, 6FFFFDC0260, 6FFFF96A3B8, 6FFFF96A3C0)
6FFFFE3FC84  0054A9DF15E (6FFFF96A3C0, 6FFFF93CA50, 0054AA3B4D0, 000FFFFFFFF)
6FFFFDC0260  0054A9BF35E (0054A9736B6, 6FFFFC5F8C0, 00600028650, 6FFFF95D9B0)
6FFFFDC0260  0054A902EF3 (6FFFFE3FC60, 6FFFFDC16E0, 0054AA3B4D0, 0054AA3B4D0)
6FFFFDC0260  0054A9C35EC (6FFFFFFE1B0, 0054AA3B040, 0054AA3DDC0, 00000000000)
6FFFF96A228  0054A9C7AFC (6FFFFE1FE68, 6FFFFF15168, 6FFFFF15168, 6FFFFDC4090)
End of stack trace (more stack frames may be present)
